---
- name: CHECK FOR PING CONNECTIVITY
  hosts: all
  gather_facts: no

  tasks:
  - name: Ping all host
    ansible.builtin.ping:    
 
   
   
- name: CHECK FOR SECURITY UPDATES
  hosts: tower-group
  gather_facts: no

  tasks:
  - name: Check Security Updates
    command: yum updateinfo list security all 
    register: out
  - debug: var=out


  
- name: CHECK DISK SPACE
  hosts: redhat-client-group
  gather_facts: no

  tasks:
  - name: Disk space
    command: free   
    register: out
  - debug: var=out.stdout_lines
  
  
  
- name: CHECK FOR YUM REPO
  hosts: ipa-rep-group
  gather_facts: no

  tasks:
  - name: Yum repolist
    command: yum repolist
    register: out
  - debug: var=out.stdout_lines
  
  

   


    




    
