---
- name: Ping
  hosts: redhat-client-group
  gather_facts: true

  tasks:
  - name: Check for connectivity
    ansible.builtin.ping:
    
    register: out
  - debug: var=out
   
  
    

    




    
